export {LoginPage} from './login'
export {RegistrationPage} from './registration'
export {Page404} from './404'
export {Page500} from './500'
export {Personal} from './personal'
export {PersonalEdit} from './personal-edit'
export {PersonalChangePass} from './personal-change-pass'
export {ChatPage} from './chat';
export {PagesLinks} from './pages-links';
